import { createContext, useContext, useState, useEffect, ReactNode } from "react";
import { useAuth } from "@/contexts/AuthContext";

type Language = "ru" | "en";

const translations = {
  ru: {
    // Header & Nav
    lang: "ru",
    skills: "Навыки",
    howItWorks: "Как это работает",
    aboutUs: "О нас",
    profile: "Профиль",
    sessions: "Сессии",
    settings: "Настройки",
    signIn: "Войти",
    signUp: "Создать аккаунт",
    signOut: "Выйти",
    start: "Начать",
    feed: "Лента",
    search: "Поиск",
    add: "Добавить",
    home: "Главная",

    // Intro & Index
    marketOfTalents: "Биржа талантов и знаний",
    skillExchangeFree: "Свободный обмен навыками",
    learnNewBySharing: "Учись новому, делясь своим",
    heroDescription: "Skillflow — платформа, где люди обмениваются знаниями и навыками напрямую. Учи программированию, музыке или языкам в обмен на то, что хочешь изучить сам.",
    createAccount: "Создать аккаунт",
    howItWorksTitle: "Как это работает",
    howItWorksSubtitle: "Простой способ учиться и делиться знаниями с единомышленниками",
    findPartner: "Найди партнёра",
    findPartnerDesc: "Умный алгоритм подберёт людей с взаимными интересами",
    exchangeSkills: "Обменяй навыки",
    exchangeSkillsDesc: "Учи других и учись сам — бесплатно и эффективно",
    reputationTitle: "Развивай репутацию",
    reputationDesc: "Получай отзывы и становись экспертом сообщества",
    safeTitle: "Безопасно",
    safeDesc: "Модерация и система отзывов защищают участников",
    readyToStart: "Готов начать обмениваться навыками?",
    joinCommunity: "Присоединяйся к сообществу и начни учиться уже сегодня",
    allRightsReserved: "Все права защищены.",

    // Auth
    welcomeBack: "С возвращением",
    enterDetailsSignIn: "Введите свои данные, чтобы войти в аккаунт",
    login: "Вход",
    registration: "Регистрация",
    email: "Email",
    password: "Пароль",
    firstName: "Имя",
    lastName: "Фамилия",
    noAccount: "Нет аккаунта?",
    haveAccount: "Уже есть аккаунт?",
    forgotPassword: "Забыли пароль?",
    processing: "Обработка...",
    invalidEmail: "Некорректный email",
    passwordMinLength: "Пароль должен быть не менее 6 символов",
    fillAllFields: "Заполните все поля",

    // Add Skill
    addNewSkill: "Добавить новый навык",
    chooseWhatYouCanTeach: "Выберите, чему вы можете научить других",
    skillTitle: "Название навыка",
    skillTitlePlaceholder: "Например: React-разработка, Игра на гитаре",
    description: "Описание",
    skillDescPlaceholder: "Расскажите подробнее о вашем опыте и чему вы можете научить...",
    category: "Категория",
    format: "Формат",
    skillLevel: "Ваш уровень",
    wantedSkills: "Что вы хотите изучить взамен?",
    wantedSkillsPlaceholder: "Например: Дизайн, Английский, Маркетинг",
    addSkillBtn: "Добавить навык",
    skillAdded: "Навык добавлен",
    skillAddedSuccess: "Ваш навык успешно добавлен в ленту",

    // Feed & Search
    communitySkills: "Навыки сообщества",
    findWhatToLearn: "Найди то, что хочешь изучить",
    addSkill: "Добавить навык",
    searchPlaceholder: "Поиск навыков...",
    noResults: "Ничего не найдено",
    tryChangeFilters: "Попробуйте изменить фильтры или поисковый запрос",
    filters: "Фильтры",
    sortBy: "Сортировать по",
    newest: "Сначала новые",
    popular: "Популярные",
    level: "Уровень",

    // Profile & User Profile
    user: "Пользователь",
    addInfoAboutYourself: "Добавьте информацию о себе в настройках профиля",
    rating: "рейтинг",
    sessionsCount: "сессий",
    skillsCount: "навыков",
    reputation: "репутация",
    mySkills: "Мои навыки",
    portfolio: "Портфолио",
    city: "Город",
    sessionHistory: "История сессий",
    reviews: "Отзывы",
    editProfile: "Редактировать профиль",
    name: "Имя",
    surname: "Фамилия",
    aboutMe: "О себе",
    yourName: "Ваше имя",
    yourSurname: "Ваша фамилия",
    tellAboutYourself: "Расскажите о себе...",
    save: "Сохранить",
    saving: "Сохранение...",
    profileUpdated: "Профиль обновлён",
    dataSaved: "Ваши данные успешно сохранены",
    error: "Ошибка",
    couldNotSave: "Не удалось сохранить изменения",
    noReviews: "Нет отзывов",
    reviewsAppearAfterSessions: "Отзывы появятся после завершённых сессий",
    noSessions: "Нет сессий",
    noSkills: "Навыков пока нет",
    noBio: "Информация отсутствует",
    back: "Назад",
    message: "Написать",
    delete: "Удалить",
    portfolio: "Портфолио",
    sessionsAppearAfterExchange: "Сессии появятся после обмена навыками",
    sessionsCompleted: "сессий проведено",
    beginner: "Начинающий",
    intermediate: "Средний",
    expert: "Эксперт",
    changeAvatar: "Сменить аватар",
    chooseAvatar: "Выберите аватар",
    defaultAvatars: "Стандартные аватары",
    photoSetup: "Настройка фото",
    dragToAlign: "Перетаскивайте фото для выравнивания",
    chooseCustomPhoto: "Выбрать свое фото",
    fileLimitInfo: "Форматы: {formats}. Макс. {size}MB",
    orChooseCharacter: "Или выберите персонажа",
    cancel: "Отмена",
    done: "Готово",
    inviteToExchange: "Предложить обмен",
    online: "В сети",
    offline: "Не в сети",
    telegram: "Telegram",
    location: "Местоположение",

    // Sessions & Exchange
    mySessions: "Мои сессии",
    manageYourSessions: "Управляйте вашими сессиями, обсуждайте детали и стройте репутацию.",
    upcoming: "Предстоящие",
    past: "Прошедшие",
    noUpcomingSessions: "Нет предстоящих сессий",
    findSkillsAndPlan: "Найдите навыки и запланируйте первую сессию",
    findSkills: "Найти навыки",
    startSession: "Начать",
    completed: "Завершено",
    rate: "Оценить",
    details: "Подробнее",
    reviewSent: "Отзыв отправлен",
    min: "мин",
    pending: "Ожидает",
    accepted: "Принято",
    rejected: "Отклонено",
    exchangeRequest: "Запрос на обмен",
    accept: "Принять",
    decline: "Отклонить",
    offerSent: "Запрос отправлен",
    offerSentSuccess: "Ваш запрос на обмен успешно отправлен",
    incoming: "Входящие",
    outgoing: "Отправленные",
    active: "Активные",
    archive: "Архив",
    noIncoming: "Входящих запросов нет",
    noOutgoing: "Вы пока ничего не отправили",
    noActive: "Активных обменов нет",
    noCompleted: "История пуста",
    loginToSeeSessions: "Войдите, чтобы увидеть сессии",
    historyDescription: "Завершенные сессии с оценками сохраняются здесь.",
    acceptedExchangeDesc: "Откройте чат, чтобы договориться о деталях",
    completeExchange: "Завершить обмен",
    loadingRequests: "Загрузка запросов...",
    partner: "Партнёр",
    from: "От",
    to: "Кому",

    // Settings
    settingsTitle: "Настройки",
    themeTitle: "Тема оформления",
    themeDescription: "Выберите предпочитаемую тему для интерфейса",
    lightTheme: "Светлая",
    lightDescription: "Классическая светлая тема",
    darkTheme: "Тёмная",
    darkDescription: "Тёмная тема для комфорта глаз",
    systemTheme: "Системная",
    systemDescription: "Следовать настройкам системы",
    notificationsTitle: "Уведомления",
    notificationsDescription: "Управление уведомлениями приложения",
    pushNotifications: "Push-уведомления",
    pushDescription: "Получать уведомления о новых сообщениях и сессиях",
    emailNotifications: "Email-уведомления",
    emailDescription: "Получать уведомления на электронную почту",
    privacyTitle: "Приватность",
    privacyDescription: "Настройки конфиденциальности профиля",
    profileVisibility: "Видимость профиля",
    profileVisibilityDescription: "Показывать профиль другим пользователям",
    onlineStatus: "Статус онлайн",
    onlineStatusDescription: "Показывать, когда вы в сети",
    languageTitle: "Язык",
    languageDescription: "Выберите язык интерфейса",
    accentColorTitle: "Цветовая палитра",
    accentColorDescription: "Выберите основной цвет приложения",
    emerald: "Изумруд",
    ocean: "Океан",
    violet: "Фиолет",
    rose: "Роза",
    amber: "Янтарь",
    slate: "Сталь",
    saved: "Сохранено",
    settingSaved: "Настройка обновлена",
    couldNotSaveSetting: "Не удалось сохранить настройку",
    inApp: "в приложении",
    inviteFriends: "Пригласить друзей",
    shareLink: "Поделитесь ссылкой, чтобы пригласить друзей в Skillflow",
    linkCopied: "Ссылка скопирована!",
    couldNotCopy: "Не удалось скопировать",
    joinSkillflow: "Присоединяйся к Skillflow — платформе обмена навыками!",
    share: "Поделиться",

    // Search
    searchSkills: "Поиск навыков",
    findWhatYouWant: "Найди именно то, что хочешь изучить",
    popularRequests: "Популярные запросы",
    results: "Результаты",
    all: "Все",
    allSkills: "Все навыки",
    nothingFound: "Ничего не найдено. Попробуйте другой запрос.",
    resetFilters: "Сбросить фильтры",
    popularSkillList: {
      design: "Дизайн",
      english: "Английский",
      guitar: "Гитара",
      photography: "Фотография",
      marketing: "Маркетинг",
      yoga: "Йога"
    },

    // Add Skill
    shareMastery: "Поделитесь своим мастерством",
    shareMasteryDesc: "Опишите свой навык и то, что вы хотели бы получить взамен. Это начало нового обмена знаниями.",
    mainInfo: "Основная информация",
    skillTitleLabel: "Название навыка *",
    skillTitlePlaceholder: "Например: React и TypeScript разработка",
    descriptionLabel: "Описание *",
    descriptionPlaceholder: "Опишите, чему вы можете научить и какой у вас опыт...",
    detailsAndFormat: "Детали и формат",
    categoryLabel: "Категория *",
    selectCategory: "Выберите категорию",
    formatLabel: "Формат занятий *",
    selectFormat: "Выберите формат",
    onlineFormat: "Онлайн (Видеосвязь)",
    offlineFormat: "Офлайн (Личная встреча)",
    bothFormats: "Любой формат",
    durationLabel: "Длительность (мин) *",
    exchangeConditions: "Условия обмена",
    wantedSkillsLabel: "Что хотите изучить взамен? *",
    wantedSkillsPlaceholder: "Например: Дизайн интерфейсов",
    wishesAppearHere: "Ваши пожелания появятся здесь...",
    wishesDesc: "Укажите навыки, которые вам интересны. Это поможет другим пользователям понять, подходит ли им ваш обмен.",
    publishToFeed: "Опубликовать в ленту",
    publishing: "Публикация...",
    skillAddedSuccessToast: "Навык добавлен!",
    skillAddedSuccessDesc: "Ваш навык виден в ленте сообщества",
    fillTitle: "Заполните название",
    fillDesc: "Добавьте описание",
    descTooLong: "Описание слишком длинное",
    maxWords: "Максимум {n} слов",
    selectCategoryToast: "Выберите категорию",
    selectFormatToast: "Выберите формат занятий",
    setDuration: "Укажите длительность от 15 до 180 минут",
    setWanted: "Укажите, что хотите взамен",
    setWantedDesc: "Это обязательное поле — добавьте хотя бы один навык",
    wordsCount: "{n} / {max} слов",
    shareSkillTitle: "Поделиться навыком",
    tellCommunity: "Расскажите сообществу, в чем вы мастер",
    whatCanYouDo: "Что вы умеете?",
    detailedDescription: "Подробное описание",
    chooseSphere: "Выберите сферу",
    whereLessons: "Где пройдут занятия?",
    approxTime: "Примерное время одной сессии (мин)",
    examplesWanted: "Например: Английский, Йога, Дизайн...",
    publishSkillBtn: "Опубликовать навык",
    refreshPage: "Обновить страницу",

    // Sessions & Notifications
    partner: "Партнёр",
    requestAccepted: "Запрос принят!",
    requestRejected: "Запрос отклонён",
    requestAcceptedMsg: "{name} принял(а) запрос на обмен «{title}». Можете начать общение.",
    requestRejectedMsg: "{name} отклонил(а) запрос на обмен «{title}».",
    sessionCompletedToast: "Сессия завершена",
    thanksForReview: "Спасибо за ваш отзыв!",

    // SkillCard
    published: "Опубликовано",
    sessionsCount: "{n} сессий",
    mySkill: "Мой",
    inExchange: "Взамен:",
    viewDetails: "Посмотреть детали",
    deleteSkillConfirm: "Удалить навык?",
    deleteSkillDesc: "Навык «{title}» будет удалён безвозвратно.",
    beginner: "Начинающий",
    intermediate: "Средний",
    expert: "Эксперт",
    preferredExchange: "Предпочтительный обмен",
    loginToMessage: "Войдите в аккаунт, чтобы написать сообщение",
    loginToExchange: "Войдите в аккаунт, чтобы предложить обмен",
    notificationSent: "Отправлено уведомление {name} (онлайн)",
    write: "Написать",
    offerExchange: "Предложить обмен",
    minLabel: "минут",

    // Chat
    emoji_smiles: "Смайлы",
    emoji_gestures: "Жесты",
    emoji_hearts: "Сердца",
    emoji_fire: "Огонь",
    emoji_food: "Еда",
    emoji_nature: "Природа",
    imageProcessingError: "Не удалось обработать изображение",
    fileReadError: "Не удалось прочитать файл",
    chatLoadError: "Не удалось загрузить чат",
    cameraAccessError: "Не удалось получить доступ к камере",
    micAccessError: "Не удалось получить доступ к микрофону",
    loginToMessageChat: "Войдите, чтобы отправить сообщение",
    chatCleared: "Чат очищен",
    today: "Сегодня",
    yesterday: "Вчера",
    chatTitle: "Чат",
    isTyping: "печатает...",
    demoChat: "Демо-чат",
    onlineStatus: "В сети",
    offlineStatus: "Не в сети",
    clearChatBtn: "Очистить чат",
    clickToDownload: "Нажмите, чтобы скачать",
    noRecipientPlaceholder: "Откройте чат из карточки навыка или раздела «Сессии»",
    startConversation: "Начните разговор — напишите первое сообщение, чтобы договориться об обмене",
    deleteForMe: "Удалить у себя",
    deleteForAll: "Удалить у всех",
    messageDeleted: "Сообщение удалено",
    sendingProgress: "Отправка...",
    videoNote: "Видеозаметка...",
    voiceMessage: "Голосовое сообщение...",
    done: "Готово",
    photoAndVideo: "Фото и видео",
    document: "Документ",
    limitInfo: "До 250 MB (до 2 мин)",
    typeMessage: "Введите сообщение",
    chatUnavailable: "Чат недоступен",
    voiceMsgTooltip: "Голосовое сообщение",
    videoNoteTooltip: "Видеозаметка",
    imageLightboxTitle: "Просмотр изображения",
    clearChatTitle: "Очистить чат",
    clearChatDesc: "Вы хотите очистить чат только у себя или у всех участников? (ваши сообщения будут удалены для всех)",
    onlyMe: "Только у меня",
    forEveryone: "У всех",

    // Portfolio
    portfolioEmpty: "Портфолио пока пусто",
    addWorkBtn: "Добавить работу ({n}/{max})",
    newWorkTitle: "Новая работа",
    workTitlePlaceholder: "Название (обязательно)",
    workDescPlaceholder: "Краткое описание (необязательно)",
    saveWorkBtn: "Сохранить",
    viewWorkTitle: "Просмотр файла",
    workAdded: "Работа добавлена",
    maxWorksReached: "Максимум {max} работ",
    fileTooLarge: "Файл слишком большой (макс. {size} МБ)",
    dragToAlign: "Перетаскивайте фото для выравнивания",
    photoSetup: "Настройка фото",
    chooseCustomPhoto: "Выбрать свое фото",
    orChooseCharacter: "или выберите персонажа",
    fileLimitInfo: "{formats} до {size}МБ",
    avatar: "Аватар",
    anonymous: "Аноним",
    someone: "Кто-то",
    user: "Пользователь",
    loading: "Загрузка…",
    commandMenu: "Меню команд",
    fileReadError: "Ошибка чтения файла",
    alternativeUploadError: "Файл слишком велик для альтернативной загрузки ({size}MB).",
    callUnavailable: "Невозможно позвонить: отсутствуют данные собеседника",
    callUserTitle: "Позвонить пользователю {name}",
    callTypeDesc: "Выберите тип звонка для обсуждения «{title}». Звонок будет выполнен прямо в приложении.",
    audioCall: "Аудиозвонок",
    videoCall: "Видеозвонок",
    exchangeAcceptedToast: "{name} принял ваш запрос на обмен!",
    exchangeRejectedToast: "Запрос на обмен отклонен",
    exchangeAcceptedSuccess: "Обмен принят!",
    exchangeAcceptError: "Ошибка при принятии обмена",
    incomingExchangeTitle: "Входящий запрос на обмен",
    exchangeOfferTitle: "Запрос на обмен!",
    exchangeOfferWants: "{name} хочет предложить вам обменяться навыком:",
    micCameraAccessError: "Не удалось получить доступ к камере или микрофону",
    callRejected: "Вызов отклонен",
    incomingCall: "Входящий {type}",
    callingPartner: "{name} звонит вам...",
    callTitle: "Вызов...",
    calling: "Звоним...",
    talking: "Идет разговор",
    skillsLoadError: "Не удалось загрузить навыки. Попробуйте обновить страницу.",
    skillAddError: "Ошибка при добавлении навыка",
    skillDeleteError: "Ошибка при удалении навыка",
    skillDeleteSuccess: "Навык удалён",
    selfExchangeError: "Нельзя предложить обмен самому себе",
    exchangeAlreadySent: "Запрос уже отправлен — ждите ответа",
    exchangeSendError: "Ошибка при отправке запроса",
    exchangeRequestTitle: "Запрос на обмен навыками",
    exchangeRequestMsg: "{name} хочет обменяться навыком «{title}». Откройте страницу «Сессии», чтобы ответить.",
    exchangeRequestNotificationTitle: "Запрос на обмен",
    exchangeRequestNotificationBody: "{name} хочет обменяться навыком «{title}»",
    exchangeRequestSent: "Запрос на обмен отправлен!",
    moderationError: "Текст содержит недопустимые выражения. Пожалуйста, соблюдайте правила сообщества.",
    meaninglessWordsError: "Пожалуйста, используйте осмысленные слова.",
    tooManyRepeatedChars: "Слишком много повторяющихся символов.",
    emptyMessageError: "Сообщение не может быть пустым",
    descriptionTooShort: "Описание слишком короткое. Добавьте больше деталей.",
    nameTooShort: "Имя слишком короткое (мин. 2 символа)",
    nameTooLong: "Имя слишком длинное (макс. 35 символов)",
    nameInvalidChars: "Имя может содержать только буквы и дефис.",
    nameMeaningless: "Пожалуйста, введите осмысленное имя.",
    nameRepeatedChars: "Имя содержит слишком много повторяющихся символов.",
    nameBlockedExpressions: "Имя содержит недопустимые выражения.",
    publicBucketError: "Пожалуйста, создайте ПУБЛИЧНЫЙ бакет 'chat_attachments' в Supabase или уменьшите размер файла.",

    // Review
    rateExchange: "Оцените обмен",
    rateDesc: "Как прошло ваше занятие с {name}? Ваша обратная связь помогает сообществу!",
    rating1: "Ужасно",
    rating2: "Плохо",
    rating3: "Нормально",
    rating4: "Хорошо",
    rating5: "Отлично!",
    yourReview: "Ваш отзыв (необязательно)",
    reviewPlaceholder: "Расскажите подробнее о вашем опыте...",
    completeSession: "Завершить сессию",
    chooseRatingError: "Пожалуйста, выберите оценку",

    // Notifications
    justNow: "только что",
    minAgo: "{n} мин назад",
    hourAgo: "{n} ч назад",
    notificationsTitle: "Уведомления",
    readAll: "Прочитать все",
    noNotifications: "Нет уведомлений",

    popularSkillList: {
      design: "Дизайн",
      english: "Английский",
      guitar: "Гитара",
      photography: "Фотография",
      marketing: "Маркетинг",
      yoga: "Йога"
    },

    // About
    openness: "Открытость",
    opennessDesc: "Мы верим, что знания должны быть доступны каждому. Skillflow — это платформа без финансовых барьеров.",
    community: "Сообщество",
    communityAboutDesc: "Мы строим пространство, где люди помогают друг другу расти и развиваться через взаимный обмен.",
    practicality: "Практичность",
    practicalityDesc: "Учёба через практику и реальное общение эффективнее любых теоретических курсов.",
    development: "Развитие",
    developmentDesc: "Каждый человек — одновременно ученик и учитель. Делясь знаниями, мы сами становимся лучше.",
    principlesTitle: "Принципы, которые направляют нас в создании лучшей платформы для обмена знаниями",

    // Auth
    chooseInterestError: "Выберите хотя бы один интерес",
    accountCreatedTitle: "Аккаунт создан!",
    accountCreatedDesc: "Добро пожаловать в Skillflow!",
    invalidEmailPassword: "Неверный email или пароль",
    emailNotConfirmed: "Email не подтверждён. Пожалуйста, проверьте вашу почту и подтвердите регистрацию.",
    welcomeBackTitle: "С возвращением!",
    welcomeBackDesc: "Вы успешно вошли в систему.",
    authRegError: "Ошибка регистрации",
    authLoginError: "Ошибка входа",
    genericAuthError: "Произошла непредвиденная ошибка",
    comingSoonTitle: "Скоро",
    resetPasswordSoon: "Восстановление пароля скоро появится",

    // How it works
    step1Title: "Создай профиль",
    step1Items: [
      "Быстрая регистрация через email или соцсети",
      "Выбери до 10 навыков для обмена",
      "Укажи уровень владения каждым навыком",
      "Добавь информацию о себе и фото"
    ],
    step2Title: "Найди партнера",
    step2Items: [
      "Умный поиск по навыкам и интересам",
      "Система совпадений по взаимным потребностям",
      "Фильтры по рейтингу, формату и доступности",
      "Мгновенные уведомления о новых совпадениях"
    ],
    step3Title: "Договорись об обмене",
    step3Items: [
      "Встроенный чат для обсуждения",
      "Календарь для планирования сессий",
      "Выбор формата: онлайн или офлайн",
      "Возможность обмена материалами"
    ],
    step4Title: "Проведи сессию",
    step4Items: [
      "Встроенный видеочат для онлайн-сессий",
      "Таймер для контроля времени",
      "Возможность записи сессии",
      "Обмен файлами и ссылками в реальном времени"
    ],
    step5Title: "Оставь отзыв",
    step5Items: [
      "Система рейтинга от 1 до 5 звёзд",
      "Текстовые отзывы о сессии",
      "Накопление репутационных очков",
      "Бейджи и достижения за активность"
    ],
    benefitsTitle: "Преимущества Skillflow",
    benefitsList: [
      "Бесплатный обмен знаниями без денежных затрат",
      "Практика с реальными людьми, а не по учебникам",
      "Расширение сети контактов и единомышленников",
      "Гибкий график — учись когда удобно",
      "Развитие навыков преподавателя",
      "Получение честной обратной связи"
    ],

    beginner: "Начинающий",
    intermediate: "Средний",
    expert: "Эксперт",
    untilNextLevel: "{current}/{next} до «{level}»",

    categories: {
      programming: "Программирование",
      design: "Дизайн",
      music: "Музыка",
      languages: "Языки",
      fitness: "Фитнес",
      photography: "Фотография",
      marketing: "Маркетинг",
      business: "Бизнес",
      art: "Искусство",
      cooking: "Кулинария",
      sport: "Спорт",
      dancing: "Танцы",
      video: "Видеомонтаж",
      writing: "Письмо и копирайтинг",
      psychology: "Психология",
      finance: "Финансы",
      education: "Наука и образование",
      crafts: "Ремёсла",
      other: "Другое"
    },

    // Chat
    typeMessage: "Напишите сообщение...",
    noMessages: "Нет сообщений",
    startConversation: "Начните общение с партнёром",
    call: "Звонок",
    video: "Видео",
    deleteForMe: "Удалить у себя",
    deleteForAll: "Удалить у всех",
    messageDeleted: "Сообщение удалено",
    clearChatTitle: "Очистить историю чата?",
    clearChatDesc: "Вы уверены, что хотите полностью очистить историю этого чата? Это действие нельзя отменить.",
    clear: "Очистить",

    // About & Info
    aboutTitle: "О Skillflow",
    aboutIntro: "Skillflow родился из идеи, что знания должны циркулировать свободно.",
    mission: "Наша миссия",
    missionText: "Создать глобальное сообщество, где каждый человек может развиваться, просто делясь тем, что он умеет лучше всего.",
    ourHistory: "Наша история",
    ourValues: "Наши ценности",
    contactUs: "Свяжитесь с нами",
    contactText: "Есть вопросы, предложения или хотите сотрудничать? Мы всегда рады обратной связи.",
    writeToUs: "Написать нам",
    telegramChat: "Telegram-чат",
    usersStatus: "пользователей",
    skillsStatus: "навыков",
    sessionsStatus: "сессий",
    ratingStatus: "рейтинг",
    aboutDescription: "Мы создаём пространство, где люди свободно обмениваются знаниями и навыками, помогая друг другу расти без финансовых барьеров.",
    simpleProcess: "Простой процесс",
    step1Title: "Создай профиль",
    step1Desc: "Зарегистрируйся и добавь навыки, которыми хочешь поделиться.",
    step2Title: "Найди партнёра",
    step2Desc: "Наш алгоритм подберёт людей с взаимными интересами.",
    step3Title: "Договорись о сессии",
    step3Desc: "Свяжись с партнёром через чат и назначь время.",
    step4Title: "Проведи сессию",
    step4Desc: "Встречайтесь онлайн или офлайн. Учитесь новому.",
    step5Title: "Получи отзыв",
    step5Desc: "Развивай репутацию и становись экспертом.",
    whySkillExchange: "Почему обмен навыками?",
    whySkillExchangeDesc: "Преимущества бартерного обучения перед традиционными курсами",
  },
  en: {
    // Header & Nav
    lang: "en",
    skills: "Skills",
    howItWorks: "How it works",
    aboutUs: "About us",
    profile: "Profile",
    sessions: "Sessions",
    settings: "Settings",
    signIn: "Sign in",
    signUp: "Create account",
    signOut: "Sign out",
    start: "Get started",
    feed: "Feed",
    search: "Search",
    add: "Add",
    home: "Home",

    // Intro & Index
    marketOfTalents: "Exchange of talents and knowledge",
    skillExchangeFree: "Free skill exchange",
    learnNewBySharing: "Learn something new by sharing your own",
    heroDescription: "Skillflow is a platform where people exchange knowledge and skills directly. Teach programming, music or languages in exchange for what you want to learn yourself.",
    createAccount: "Create account",
    howItWorksTitle: "How it works",
    howItWorksSubtitle: "A simple way to learn and share knowledge with like-minded people",
    findPartner: "Find a partner",
    findPartnerDesc: "A smart algorithm will find people with mutual interests",
    exchangeSkills: "Exchange skills",
    exchangeSkillsDesc: "Teach others and learn yourself — free and effective",
    reputationTitle: "Build reputation",
    reputationDesc: "Get reviews and become a community expert",
    safeTitle: "Safe",
    safeDesc: "Moderation and review system protect participants",
    readyToStart: "Ready to start exchanging skills?",
    joinCommunity: "Join the community and start learning today",
    allRightsReserved: "All rights reserved.",

    // Auth
    welcomeBack: "Welcome back",
    enterDetailsSignIn: "Enter your details to sign in",
    login: "Login",
    registration: "Registration",
    email: "Email",
    password: "Password",
    firstName: "First Name",
    lastName: "Last Name",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    forgotPassword: "Forgot password?",
    processing: "Processing...",
    invalidEmail: "Invalid email",
    passwordMinLength: "Password must be at least 6 characters",
    fillAllFields: "Please fill all fields",

    // Add Skill
    addNewSkill: "Add new skill",
    chooseWhatYouCanTeach: "Choose what you can teach others",
    skillTitle: "Skill title",
    skillTitlePlaceholder: "Example: React development, Playing guitar",
    description: "Description",
    skillDescPlaceholder: "Tell more about your experience and what you can teach...",
    category: "Category",
    format: "Format",
    skillLevel: "Your level",
    wantedSkills: "What do you want to learn in return?",
    wantedSkillsPlaceholder: "Example: Design, English, Marketing",
    addSkillBtn: "Add skill",
    skillAdded: "Skill added",
    skillAddedSuccess: "Your skill has been successfully added to the feed",

    // Feed & Search
    communitySkills: "Community Skills",
    findWhatToLearn: "Find what you want to learn",
    addSkill: "Add skill",
    searchPlaceholder: "Search skills...",
    noResults: "Nothing found",
    tryChangeFilters: "Try changing filters or search query",
    filters: "Filters",
    sortBy: "Sort by",
    newest: "Newest",
    popular: "Popular",
    level: "Level",

    // Profile & User Profile
    user: "User",
    addInfoAboutYourself: "Add information about yourself in profile settings",
    rating: "rating",
    sessionsCount: "sessions",
    skillsCount: "skills",
    reputation: "reputation",
    mySkills: "My Skills",
    portfolio: "Portfolio",
    city: "City",
    sessionHistory: "Session History",
    reviews: "Reviews",
    editProfile: "Edit Profile",
    name: "First name",
    surname: "Last name",
    aboutMe: "About me",
    yourName: "Your name",
    yourSurname: "Your last name",
    tellAboutYourself: "Tell about yourself...",
    save: "Save",
    saving: "Saving...",
    profileUpdated: "Profile updated",
    dataSaved: "Your data has been saved",
    error: "Error",
    couldNotSave: "Could not save changes",
    noReviews: "No reviews",
    reviewsAppearAfterSessions: "Reviews will appear after completed sessions",
    noSessions: "No sessions",
    noSkills: "No skills yet",
    noBio: "No information provided",
    back: "Back",
    message: "Message",
    delete: "Delete",
    portfolio: "Portfolio",
    sessionsAppearAfterExchange: "Sessions will appear after skill exchanges",
    sessionsCompleted: "sessions completed",
    beginner: "Beginner",
    intermediate: "Intermediate",
    expert: "Expert",
    changeAvatar: "Change avatar",
    chooseAvatar: "Choose avatar",
    defaultAvatars: "Default avatars",
    photoSetup: "Setup Photo",
    dragToAlign: "Drag photo to align",
    chooseCustomPhoto: "Choose custom photo",
    fileLimitInfo: "Formats: {formats}. Max. {size}MB",
    orChooseCharacter: "Or choose a character",
    cancel: "Cancel",
    done: "Done",
    inviteToExchange: "Offer exchange",
    online: "Online",
    offline: "Offline",
    telegram: "Telegram",
    location: "Location",

    // Sessions & Exchange
    mySessions: "My Sessions",
    manageYourSessions: "Manage your sessions, discuss details and build reputation.",
    upcoming: "Upcoming",
    past: "Past",
    noUpcomingSessions: "No upcoming sessions",
    findSkillsAndPlan: "Find skills and plan your first session",
    findSkills: "Find skills",
    startSession: "Start",
    completed: "Completed",
    rate: "Rate",
    details: "Details",
    reviewSent: "Review sent",
    min: "min",
    pending: "Pending",
    accepted: "Accepted",
    rejected: "Rejected",
    exchangeRequest: "Exchange Request",
    accept: "Accept",
    decline: "Decline",
    offerSent: "Request sent",
    offerSentSuccess: "Your exchange request has been sent successfully",
    incoming: "Incoming",
    outgoing: "Outgoing",
    active: "Active",
    archive: "Archive",
    noIncoming: "No incoming requests",
    noOutgoing: "You haven't sent anything yet",
    noActive: "No active exchanges",
    noCompleted: "History is empty",
    loginToSeeSessions: "Login to see sessions",
    historyDescription: "Completed sessions with ratings are saved here.",
    acceptedExchangeDesc: "Open chat to agree on details",
    completeExchange: "Complete exchange",
    loadingRequests: "Loading requests...",
    partner: "Partner",
    from: "From",
    to: "To",

    // Settings
    settingsTitle: "Settings",
    themeTitle: "Theme",
    themeDescription: "Choose your preferred interface theme",
    lightTheme: "Light",
    lightDescription: "Classic light theme",
    darkTheme: "Dark",
    darkDescription: "Dark theme for eye comfort",
    systemTheme: "System",
    systemDescription: "Follow system settings",
    notificationsTitle: "Notifications",
    notificationsDescription: "Manage app notifications",
    pushNotifications: "Push notifications",
    pushDescription: "Receive notifications about new messages and sessions",
    emailNotifications: "Email notifications",
    emailDescription: "Receive notifications via email",
    privacyTitle: "Privacy",
    privacyDescription: "Profile privacy settings",
    profileVisibility: "Profile visibility",
    profileVisibilityDescription: "Show profile to other users",
    onlineStatus: "Online status",
    onlineStatusDescription: "Show when you are online",
    languageTitle: "Language",
    languageDescription: "Choose interface language",
    accentColorTitle: "Color Palette",
    accentColorDescription: "Choose the primary accent color for the app",
    emerald: "Emerald",
    ocean: "Ocean",
    violet: "Violet",
    rose: "Rose",
    amber: "Amber",
    slate: "Slate",
    saved: "Saved",
    settingSaved: "Setting updated",
    couldNotSaveSetting: "Could not save setting",
    inApp: "in app",
    inviteFriends: "Invite Friends",
    shareLink: "Share the link to invite friends to Skillflow",
    linkCopied: "Link copied!",
    couldNotCopy: "Could not copy link",
    joinSkillflow: "Join Skillflow — a skill exchange platform!",
    share: "Share",

    // Search
    searchSkills: "Search Skills",
    findWhatYouWant: "Find exactly what you want to learn",
    popularRequests: "Popular requests",
    results: "Results",
    all: "All",
    allSkills: "All Skills",
    nothingFound: "Nothing found. Try another query.",
    resetFilters: "Reset filters",
    popularSkillList: {
      design: "Design",
      english: "English",
      guitar: "Guitar",
      photography: "Photography",
      marketing: "Marketing",
      yoga: "Yoga"
    },

    // Add Skill
    shareMastery: "Share your mastery",
    shareMasteryDesc: "Describe your skill and what you would like to receive or learn in return. This is the start of a new knowledge exchange.",
    mainInfo: "Main information",
    skillTitleLabel: "Skill title *",
    skillTitlePlaceholder: "Example: React and TypeScript development",
    descriptionLabel: "Description *",
    descriptionPlaceholder: "Describe what you can teach and what experience you have...",
    detailsAndFormat: "Details and format",
    categoryLabel: "Category *",
    selectCategory: "Select category",
    formatLabel: "Lesson format *",
    selectFormat: "Select format",
    onlineFormat: "Online (Video call)",
    offlineFormat: "Offline (In-person meeting)",
    bothFormats: "Any format",
    durationLabel: "Duration (min) *",
    exchangeConditions: "Exchange conditions",
    wantedSkillsLabel: "What do you want to learn in return? *",
    wantedSkillsPlaceholder: "Example: UI Design",
    wishesAppearHere: "Your wishes will appear here...",
    wishesDesc: "List the skills you are interested in. This will help other users understand if your exchange suits them.",
    publishToFeed: "Publish to feed",
    publishing: "Publishing...",
    skillAddedSuccessToast: "Skill added!",
    skillAddedSuccessDesc: "Your skill is visible in the community feed",
    fillTitle: "Fill in the title",
    fillDesc: "Add a description",
    descTooLong: "Description too long",
    maxWords: "Maximum {n} words",
    selectCategoryToast: "Select a category",
    selectFormatToast: "Select lesson format",
    setDuration: "Specify duration from 15 to 180 minutes",
    setWanted: "Specify what you want in return",
    setWantedDesc: "This is a required field — add at least one skill",
    wordsCount: "{n} / {max} words",
    shareSkillTitle: "Share a skill",
    tellCommunity: "Tell the community what you are a master of",
    whatCanYouDo: "What can you do?",
    detailedDescription: "Detailed description",
    chooseSphere: "Choose a sphere",
    whereLessons: "Where will the lessons be?",
    approxTime: "Approximate time of one session (min)",
    examplesWanted: "Example: English, Yoga, Design...",
    publishSkillBtn: "Publish skill",
    refreshPage: "Refresh page",

    // Sessions & Notifications
    partner: "Partner",
    requestAccepted: "Request accepted!",
    requestRejected: "Request rejected",
    requestAcceptedMsg: "{name} accepted the exchange request for \"{title}\". You can start chatting.",
    requestRejectedMsg: "{name} rejected the exchange request for \"{title}\".",
    sessionCompletedToast: "Session completed",
    thanksForReview: "Thanks for your review!",

    // SkillCard
    published: "Published",
    sessionsCount: "{n} sessions",
    mySkill: "My",
    inExchange: "In exchange:",
    viewDetails: "View details",
    deleteSkillConfirm: "Delete skill?",
    deleteSkillDesc: "Skill \"{title}\" will be deleted permanently.",
    beginner: "Beginner",
    intermediate: "Intermediate",
    expert: "Expert",
    preferredExchange: "Preferred exchange",
    loginToMessage: "Sign in to send a message",
    loginToExchange: "Sign in to suggest an exchange",
    notificationSent: "Notification sent to {name} (online)",
    write: "Message",
    offerExchange: "Suggest exchange",
    minLabel: "minutes",

    // Chat
    emoji_smiles: "Smiles",
    emoji_gestures: "Gestures",
    emoji_hearts: "Hearts",
    emoji_fire: "Fire",
    emoji_food: "Food",
    emoji_nature: "Nature",
    imageProcessingError: "Failed to process image",
    fileReadError: "Failed to read file",
    chatLoadError: "Failed to load chat",
    cameraAccessError: "Failed to access camera",
    micAccessError: "Failed to access microphone",
    loginToMessageChat: "Sign in to send a message",
    chatCleared: "Chat cleared",
    today: "Today",
    yesterday: "Yesterday",
    chatTitle: "Chat",
    isTyping: "typing...",
    demoChat: "Demo Chat",
    onlineStatus: "Online",
    offlineStatus: "Offline",
    clearChatBtn: "Clear chat",
    clickToDownload: "Click to download",
    noRecipientPlaceholder: "Open a chat from a skill card or the Sessions section",
    startConversation: "Start a conversation — send your first message to agree on an exchange",
    deleteForMe: "Delete for me",
    deleteForAll: "Delete for all",
    messageDeleted: "Message deleted",
    sendingProgress: "Sending...",
    videoNote: "Video note...",
    voiceMessage: "Voice message...",
    done: "Done",
    photoAndVideo: "Photo & video",
    document: "Document",
    limitInfo: "Up to 250 MB (up to 2 min)",
    typeMessage: "Type a message",
    chatUnavailable: "Chat unavailable",
    voiceMsgTooltip: "Voice message",
    videoNoteTooltip: "Video note",
    imageLightboxTitle: "View image",
    clearChatTitle: "Clear chat",
    clearChatDesc: "Do you want to clear the chat for yourself only or for all participants? (your messages will be deleted for everyone)",
    onlyMe: "Only for me",
    forEveryone: "For everyone",

    // Portfolio
    portfolioEmpty: "Portfolio is empty for now",
    addWorkBtn: "Add work ({n}/{max})",
    newWorkTitle: "New work",
    workTitlePlaceholder: "Title (required)",
    workDescPlaceholder: "Short description (optional)",
    saveWorkBtn: "Save",
    viewWorkTitle: "View file",
    workAdded: "Work added",
    maxWorksReached: "Maximum {max} works",
    fileTooLarge: "File too large (max {size} MB)",
    dragToAlign: "Drag photo to align",
    photoSetup: "Setup photo",
    chooseCustomPhoto: "Choose your photo",
    orChooseCharacter: "or choose a character",
    fileLimitInfo: "{formats} up to {size}MB",
    avatar: "Avatar",
    anonymous: "Anonymous",
    someone: "Someone",
    user: "User",
    loading: "Loading…",
    commandMenu: "Command Menu",
    fileReadError: "File read error",
    alternativeUploadError: "File too large for alternative upload ({size}MB).",
    callUnavailable: "Call unavailable: partner data missing",
    callUserTitle: "Call user {name}",
    callTypeDesc: "Choose call type to discuss \"{title}\". The call will be made directly in the app.",
    audioCall: "Audio call",
    videoCall: "Video call",
    exchangeAcceptedToast: "{name} accepted your exchange request!",
    exchangeRejectedToast: "Exchange request rejected",
    exchangeAcceptedSuccess: "Exchange accepted!",
    exchangeAcceptError: "Error accepting exchange",
    incomingExchangeTitle: "Incoming exchange request",
    exchangeOfferTitle: "Exchange request!",
    exchangeOfferWants: "{name} wants to offer you a skill exchange:",
    micCameraAccessError: "Could not access camera or microphone",
    callRejected: "Call rejected",
    incomingCall: "Incoming {type}",
    callingPartner: "{name} is calling you...",
    callTitle: "Call...",
    calling: "Calling...",
    talking: "Talking",
    skillsLoadError: "Could not load skills. Please refresh the page.",
    skillAddError: "Error adding skill",
    skillDeleteError: "Error deleting skill",
    skillDeleteSuccess: "Skill deleted",
    selfExchangeError: "Cannot offer exchange to yourself",
    exchangeAlreadySent: "Request already sent — please wait for answer",
    exchangeSendError: "Error sending request",
    exchangeRequestTitle: "Skill exchange request",
    exchangeRequestMsg: "{name} wants to exchange skills \"{title}\". Open \"Sessions\" to respond.",
    exchangeRequestNotificationTitle: "Exchange request",
    exchangeRequestNotificationBody: "{name} wants to exchange skills \"{title}\"",
    exchangeRequestSent: "Exchange request sent!",
    moderationError: "Text contains inadmissible expressions. Please follow community rules.",
    meaninglessWordsError: "Please use meaningful words.",
    tooManyRepeatedChars: "Too many repeated characters.",
    emptyMessageError: "Message cannot be empty",
    descriptionTooShort: "Description too short. Add more details.",
    nameTooShort: "Name too short (min. 2 characters)",
    nameTooLong: "Name too long (max. 35 characters)",
    nameInvalidChars: "Name can only contain letters and hyphen.",
    nameMeaningless: "Please enter a meaningful name.",
    nameRepeatedChars: "Name contains too many repeated characters.",
    nameBlockedExpressions: "Name contains inadmissible expressions.",
    publicBucketError: "Please create a PUBLIC bucket 'chat_attachments' in Supabase or reduce file size.",

    // Review
    rateExchange: "Rate the exchange",
    rateDesc: "How was your session with {name}? Your feedback helps the community!",
    rating1: "Terrible",
    rating2: "Poor",
    rating3: "Normal",
    rating4: "Good",
    rating5: "Excellent!",
    yourReview: "Your review (optional)",
    reviewPlaceholder: "Tell us more about your experience...",
    completeSession: "Complete session",
    chooseRatingError: "Please choose a rating",

    // Notifications
    justNow: "just now",
    minAgo: "{n} m ago",
    hourAgo: "{n} h ago",
    notificationsTitle: "Notifications",
    readAll: "Read all",
    noNotifications: "No notifications",

    popularSkillList: {
      design: "Design",
      english: "English",
      guitar: "Guitar",
      photography: "Photography",
      marketing: "Marketing",
      yoga: "Yoga"
    },

    // About
    openness: "Openness",
    opennessDesc: "We believe that knowledge should be accessible to everyone. Skillflow is a platform without financial barriers.",
    community: "Community",
    communityAboutDesc: "We building a space where people help each other grow and develop through mutual exchange.",
    practicality: "Practicality",
    practicalityDesc: "Learning through practice and real communication is more effective than any theoretical courses.",
    development: "Development",
    developmentDesc: "Every person is both a student and a teacher. By sharing knowledge, we become better ourselves.",
    principlesTitle: "Principles that guide us in creating the best platform for knowledge exchange",

    // Auth
    chooseInterestError: "Select at least one interest",
    accountCreatedTitle: "Account created!",
    accountCreatedDesc: "Welcome to Skillflow!",
    invalidEmailPassword: "Invalid email or password",
    emailNotConfirmed: "Email not confirmed. Please check your email and confirm registration.",
    welcomeBackTitle: "Welcome back!",
    welcomeBackDesc: "You have successfully logged in.",
    authRegError: "Registration error",
    authLoginError: "Login error",
    genericAuthError: "An unexpected error occurred",
    comingSoonTitle: "Soon",
    resetPasswordSoon: "Password reset will be available soon",

    // How it works
    step1Title: "Create profile",
    step1Items: [
      "Fast registration via email or social networks",
      "Choose up to 10 skills for exchange",
      "Specify proficiency level for each skill",
      "Add info about yourself and a photo"
    ],
    step2Title: "Find a partner",
    step2Items: [
      "Smart search by skills and interests",
      "Matching system by mutual needs",
      "Filters by rating, format and accessibility",
      "Instant notifications about new matches"
    ],
    step3Title: "Agree on exchange",
    step3Items: [
      "Built-in chat for discussion",
      "Calendar for session planning",
      "Choice of format: online or offline",
      "Ability to exchange materials"
    ],
    step4Title: "Conduct session",
    step4Items: [
      "Built-in video chat for online sessions",
      "Timer for time control",
      "Ability to record session",
      "Real-time file and link exchange"
    ],
    step5Title: "Leave a review",
    step5Items: [
      "Rating system from 1 to 5 stars",
      "Text reviews about the session",
      "Accumulation of reputation points",
      "Badges and achievements for activity"
    ],
    benefitsTitle: "Advantages of Skillflow",
    benefitsList: [
      "Free knowledge exchange without monetary costs",
      "Practice with real people, not textbooks",
      "Expanding the network of contacts and like-minded people",
      "Flexible schedule — learn when it's convenient",
      "Development of teaching skills",
      "Getting honest feedback"
    ],

    beginner: "Beginner",
    intermediate: "Intermediate",
    expert: "Expert",
    untilNextLevel: "{current}/{next} until \"{level}\"",

    categories: {
      programming: "Programming",
      design: "Design",
      music: "Music",
      languages: "Languages",
      fitness: "Fitness",
      photography: "Photography",
      marketing: "Marketing",
      business: "Business",
      art: "Art",
      cooking: "Cooking",
      sport: "Sport",
      dancing: "Dancing",
      video: "Video Editing",
      writing: "Writing & Copywriting",
      psychology: "Psychology",
      finance: "Finance",
      education: "Science & Education",
      crafts: "Crafts",
      other: "Other"
    },

    // Chat
    typeMessage: "Type a message...",
    noMessages: "No messages",
    startConversation: "Start a conversation with your partner",
    call: "Call",
    video: "Video",
    deleteForMe: "Delete for me",
    deleteForAll: "Delete for everyone",
    messageDeleted: "Message deleted",
    clearChatTitle: "Clear chat history?",
    clearChatDesc: "Are you sure you want to completely clear this chat history? This action cannot be undone.",
    clear: "Clear",

    // About & Info
    aboutTitle: "About Skillflow",
    aboutIntro: "Skillflow was born from the idea that knowledge should circulate freely.",
    mission: "Our Mission",
    missionText: "To create a global community where everyone can grow by simply sharing what they do best.",
    ourHistory: "Our Story",
    ourValues: "Our Values",
    contactUs: "Contact Us",
    contactText: "Have questions, suggestions or want to cooperate? We are always happy to hear from you.",
    writeToUs: "Write to us",
    telegramChat: "Telegram chat",
    usersStatus: "users",
    skillsStatus: "skills",
    sessionsStatus: "sessions",
    ratingStatus: "rating",
    aboutDescription: "We create a space where people freely exchange knowledge and skills, helping each other grow without financial barriers.",
    simpleProcess: "Simple process",
    step1Title: "Create profile",
    step1Desc: "Sign up and add skills you want to share.",
    step2Title: "Find a partner",
    step2Desc: "Our algorithm will find people with mutual interests.",
    step3Title: "Agree on session",
    step3Desc: "Chat with your partner and set a time.",
    step4Title: "Conduct session",
    step4Desc: "Meet online or offline. Learn new things.",
    step5Title: "Get feedback",
    step5Desc: "Build your reputation and become an expert.",
    whySkillExchange: "Why skill exchange?",
    whySkillExchangeDesc: "Advantages of barter learning over traditional courses",
  },
} as const;

type TranslationKey = keyof typeof translations.ru;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const { user } = useAuth();
  const [language, setLanguageState] = useState<Language>(
    () => (user?.user_metadata?.language as Language) || "ru"
  );

  useEffect(() => {
    const lang = user?.user_metadata?.language;
    if (lang === "ru" || lang === "en") {
      setLanguageState(lang);
    }
  }, [user?.user_metadata?.language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: any): any => {
    const keys = String(key).split(".");
    let value: any = translations[language];
    for (const k of keys) {
      if (value !== undefined) value = value[k];
      else break;
    }
    
    if (value !== undefined) return value;
    
    let valueRu: any = translations.ru;
    for (const k of keys) {
      if (valueRu !== undefined) valueRu = valueRu[k];
      else break;
    }
    
    return valueRu !== undefined ? valueRu : key;
  };

  return (
    <LanguageContext.Provider value={{ language, t, setLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};
