import { createContext, useContext, useState, useEffect, ReactNode } from "react";
import { useAuth } from "@/contexts/AuthContext";

type Language = "ru" | "en";

const translations = {
  ru: {
    // Header & Nav
    skills: "Навыки",
    howItWorks: "Как это работает",
    aboutUs: "О нас",
    profile: "Профиль",
    sessions: "Сессии",
    settings: "Настройки",
    signIn: "Войти",
    signUp: "Создать аккаунт",
    signOut: "Выйти",
    start: "Начать",
    feed: "Лента",
    search: "Поиск",
    add: "Добавить",
    home: "Главная",

    // Intro & Index
    marketOfTalents: "Биржа талантов и знаний",
    skillExchangeFree: "Свободный обмен навыками",
    learnNewBySharing: "Учись новому, делясь своим",
    heroDescription: "Skillflow — платформа, где люди обмениваются знаниями и навыками напрямую. Учи программированию, музыке или языкам в обмен на то, что хочешь изучить сам.",
    createAccount: "Создать аккаунт",
    howItWorksTitle: "Как это работает",
    howItWorksSubtitle: "Простой способ учиться и делиться знаниями с единомышленниками",
    findPartner: "Найди партнёра",
    findPartnerDesc: "Умный алгоритм подберёт людей с взаимными интересами",
    exchangeSkills: "Обменяй навыки",
    exchangeSkillsDesc: "Учи других и учись сам — бесплатно и эффективно",
    reputationTitle: "Развивай репутацию",
    reputationDesc: "Получай отзывы и становись экспертом сообщества",
    safeTitle: "Безопасно",
    safeDesc: "Система отзывов и история обменов защищают участников",
    readyToStart: "Готов начать обмениваться навыками?",
    joinCommunity: "Присоединяйся к сообществу и начни учиться уже сегодня",
    allRightsReserved: "Все права защищены.",

    // Auth
    welcomeBack: "С возвращением",
    enterDetailsSignIn: "Введите свои данные, чтобы войти в аккаунт",
    login: "Вход",
    registration: "Регистрация",
    email: "Email",
    password: "Пароль",
    firstName: "Имя",
    lastName: "Фамилия",
    noAccount: "Нет аккаунта?",
    haveAccount: "Уже есть аккаунт?",
    forgotPassword: "Забыли пароль?",
    processing: "Обработка...",
    invalidEmail: "Некорректный email",
    passwordMinLength: "Пароль должен быть не менее 6 символов",
    passwordsDoNotMatch: "Пароли не совпадают",
    fillAllFields: "Заполните все поля",
    chooseInterestError: "Выберите хотя бы один интерес",
    maxSkillsError: "Максимум 5 навыков",
    accountCreatedTitle: "Аккаунт создан!",
    accountCreatedDesc: "Добро пожаловать в Skillflow!",
    invalidEmailPassword: "Неверный email или пароль",
    emailNotConfirmed: "Email не подтверждён. Пожалуйста, проверьте вашу почту.",
    welcomeBackTitle: "С возвращением!",
    welcomeBackDesc: "Вы успешно вошли в систему.",
    authRegError: "Ошибка регистрации",
    authLoginError: "Ошибка входа",
    genericAuthError: "Произошла непредвиденная ошибка",
    networkError: "Ошибка сети. Не удалось связаться с сервером. Проверьте интернет-соединение.",
    comingSoonTitle: "Скоро",
    resetPasswordSoon: "Восстановление пароля скоро появится",

    // Add Skill
    addNewSkill: "Добавить новый навык",
    chooseWhatYouCanTeach: "Выберите, чему вы можете научить других",
    skillTitle: "Название навыка",
    skillTitleLabel: "Название навыка *",
    skillTitlePlaceholder: "Например: React и TypeScript разработка",
    description: "Описание",
    descriptionLabel: "Описание *",
    descriptionPlaceholder: "Расскажите подробнее о вашем опыте и чему вы можете научить...",
    category: "Категория",
    categoryLabel: "Категория *",
    selectCategory: "Выберите категорию",
    format: "Формат",
    formatLabel: "Формат занятий *",
    selectFormat: "Выберите формат",
    onlineFormat: "Онлайн (Видеосвязь)",
    offlineFormat: "Офлайн (Личная встреча)",
    bothFormats: "Любой формат",
    durationLabel: "Длительность (мин) *",
    skillLevel: "Ваш уровень",
    wantedSkills: "Что вы хотите изучить взамен?",
    wantedSkillsLabel: "Что хотите изучить взамен? *",
    wantedSkillsPlaceholder: "Например: Дизайн интерфейсов",
    addSkillBtn: "Добавить навык",
    skillAdded: "Навык добавлен",
    skillAddedSuccess: "Ваш навык успешно добавлен в ленту",
    shareMastery: "Поделитесь своим мастерством",
    shareMasteryDesc: "Опишите свой навык и то, что вы хотели бы получить взамен.",
    mainInfo: "Основная информация",
    detailsAndFormat: "Детали и формат",
    exchangeConditions: "Условия обмена",
    wishesAppearHere: "Ваши пожелания появятся здесь...",
    wishesDesc: "Укажите навыки, которые вам интересны.",
    publishToFeed: "Опубликовать в ленту",
    publishing: "Публикация...",
    skillAddedSuccessToast: "Навык добавлен!",
    skillAddedSuccessDesc: "Ваш навык виден в ленте сообщества",
    fillTitle: "Заполните название",
    fillDesc: "Добавьте описание",
    descTooLong: "Описание слишком длинное",
    maxWords: "Максимум {n} слов",
    selectCategoryToast: "Выберите категорию",
    selectFormatToast: "Выберите формат занятий",
    setDuration: "Укажите длительность от 15 до 180 минут",
    setWanted: "Укажите, что хотите взамен",
    setWantedDesc: "Это обязательное поле — добавьте хотя бы один навык",
    wordsCount: "{n} / {max} слов",
    shareSkillTitle: "Поделиться навыком",
    tellCommunity: "Расскажите сообществу, в чем вы мастер",
    whatCanYouDo: "Что вы умеете?",
    detailedDescription: "Подробное описание",
    chooseSphere: "Выберите сферу",
    whereLessons: "Где пройдут занятия?",
    approxTime: "Время одной сессии (мин)",
    examplesWanted: "Например: Английский, Гитара...",
    publishSkillBtn: "Опубликовать навык",
    refreshPage: "Обновить страницу",
    skillsLoadError: "Ошибка загрузки навыков",
    skillAddError: "Не удалось добавить навык",
    skillDeleteError: "Не удалось удалить навык",
    skillDeleteSuccess: "Навык удалён",
    selfExchangeError: "Нельзя предлагать обмен самому себе",
    exchangeAlreadySent: "Запрос уже отправлен",
    exchangeSendError: "Ошибка отправки запроса",
    networkError: "Ошибка сетевого соединения. Проверьте интернет или попробуйте позже.",
    exchangeRequestSent: "Запрос на обмен отправлен",

    // Feed & Search
    communitySkills: "Навыки сообщества",
    findWhatToLearn: "Найди то, что хочешь изучить",
    searchPlaceholder: "Поиск навыков...",
    noResults: "Ничего не найдено",
    noSkillsFound: "Навыки не найдены.",
    tryChangeFilters: "Попробуйте изменить фильтры",
    popularRequests: "Популярные запросы",
    resetFilters: "Сбросить фильтры",
    popularSkillList: {
      design: "Дизайн",
      english: "Английский",
      guitar: "Гитара",
      photography: "Фотография",
      marketing: "Маркетинг",
      yoga: "Йога"
    },
    filters: "Фильтры",
    sortBy: "Сортировать по",
    newest: "Сначала новые",
    popular: "Популярные",
    level: "Уровень",
    all: "Все",
    allSkills: "Все навыки",

    // Profile & User Profile
    addInfoAboutYourself: "Добавьте информацию о себе в настройках",
    rating: "рейтинг",
    sessionsCount: "{n} сессий",
    skillsCount: "{n} навыков",
    reputation: "репутация",
    mySkills: "Мои навыки",
    portfolio: "Портфолио",
    city: "Город",
    sessionHistory: "История сессий",
    reviews: "Отзывы",
    editProfile: "Редактировать профиль",
    name: "Имя",
    surname: "Фамилия",
    aboutMe: "О себе",
    yourName: "Ваше имя",
    yourSurname: "Ваша фамилия",
    tellAboutYourself: "Расскажите о себе...",
    save: "Сохранить",
    saving: "Сохранение...",
    profileUpdated: "Профиль обновлён",
    dataSaved: "Ваши данные успешно сохранены",
    error: "Ошибка",
    couldNotSave: "Не удалось сохранить изменения",
    noReviews: "Нет отзывов",
    reviewsAppearAfterSessions: "Отзывы появятся после завершённых сессий",
    noSessions: "Нет сессий",
    noSkills: "Навыков пока нет",
    noBio: "Информация отсутствует",
    back: "Назад",
    message: "Написать",
    delete: "Удалить",
    sessionsAppearAfterExchange: "Сессии появятся после обмена навыками",
    sessionsCompleted: "сессий проведено",
    beginner: "Начинающий",
    intermediate: "Средний",
    expert: "Эксперт",
    changeAvatar: "Сменить аватар",
    chooseAvatar: "Выберите аватар",
    defaultAvatars: "Стандартные аватары",
    photoSetup: "Настройка фото",
    dragToAlign: "Перетаскивайте фото для выравнивания",
    chooseCustomPhoto: "Выбрать свое фото",
    fileLimitInfo: "Форматы: {formats}. Макс. {size}MB",
    orChooseCharacter: "Или выберите персонажа",
    cancel: "Отмена",
    done: "Готово",
    inviteToExchange: "Предложить обмен",
    online: "В сети",
    offline: "Не в сети",
    telegram: "Telegram",
    location: "Местоположение",
    avatar: "Аватар",
    anonymous: "Аноним",
    someone: "Кто-то",
    user: "Пользователь",

    // Sessions & Exchange
    mySessions: "Мои сессии",
    manageYourSessions: "Управляйте вашими сессиями и стройте репутацию.",
    upcoming: "Предстоящие",
    past: "Прошедшие",
    noUpcomingSessions: "Нет предстоящих сессий",
    findSkillsAndPlan: "Найдите навыки и запланируйте первую сессию",
    findSkills: "Найти навыки",
    startSession: "Начать",
    completed: "Завершено",
    rate: "Оценить",
    details: "Подробнее",
    reviewSent: "Отзыв отправлен",
    min: "мин",
    pending: "Ожидает",
    accepted: "Принято",
    rejected: "Отклонено",
    exchangeRequest: "Запрос на обмен",
    accept: "Принять",
    decline: "Отклонить",
    offerSent: "Запрос отправлен",
    offerSentSuccess: "Ваш запрос успешно отправлен",
    incoming: "Входящие",
    outgoing: "Отправленные",
    active: "Активные",
    archive: "Архив",
    noIncoming: "Входящих запросов нет",
    noOutgoing: "Вы пока ничего не отправили",
    noActive: "Активных обменов нет",
    noCompleted: "История пуста",
    loginToSeeSessions: "Войдите, чтобы увидеть сессии",
    historyDescription: "Завершенные сессии сохраняются здесь.",
    acceptedExchangeDesc: "Откройте чат, чтобы договориться о деталях",
    completeExchange: "Завершить обмен",
    loadingRequests: "Загрузка запросов...",
    partner: "Партнёр",
    from: "От",
    to: "Кому",
    requestAccepted: "Запрос принят!",
    requestRejected: "Запрос отклонён",
    requestAcceptedMsg: "{name} принял(а) запрос. Можете начать общение.",
    requestRejectedMsg: "{name} отклонил(а) запрос.",
    sessionCompletedToast: "Сессия завершена",
    thanksForReview: "Спасибо за ваш отзыв!",
    viewDetails: "Посмотреть детали",
    exchangeRequestTitle: "Новый запрос на обмен",
    exchangeRequestMsg: "{name} хочет обменяться навыками: {title}",
    exchangeRequestNotificationTitle: "Запрос на обмен",
    exchangeRequestNotificationBody: "{name} предложил обмен для навыка {title}",
    deleteSkillConfirm: "Удалить навык?",
    deleteSkillDesc: "Навык «{title}» будет удалён безвозвратно.",
    preferredExchange: "Предпочтительный обмен",
    loginToMessage: "Войдите, чтобы написать сообщение",
    loginToExchange: "Войдите, чтобы предложить обмен",
    notificationSent: "Уведомление отправлено",
    write: "Написать",
    offerExchange: "Предложить обмен",
    minLabel: "минут",

    // Chat & Calls
    emoji_smiles: "Смайлы",
    emoji_gestures: "Жесты",
    emoji_hearts: "Сердца",
    emoji_fire: "Огонь",
    emoji_food: "Еда",
    emoji_nature: "Природа",
    imageProcessingError: "Ошибка обработки изображения",
    fileReadError: "Ошибка чтения файла",
    chatLoadError: "Ошибка загрузки чата",
    cameraAccessError: "Нет доступа к камере",
    micAccessError: "Нет доступа к микрофону",
    loginToMessageChat: "Войдите, чтобы отправить сообщение",
    chatCleared: "Чат очищен",
    today: "Сегодня",
    yesterday: "Вчера",
    chatTitle: "Чат",
    isTyping: "печатает...",
    demoChat: "Демо-чат",
    onlineStatus: "В сети",
    offlineStatus: "Не в сети",
    clearChatBtn: "Очистить чат",
    clickToDownload: "Скачать",
    noRecipientPlaceholder: "Выберите собеседника",
    startConversation: "Начните общение",
    deleteForMe: "Удалить у себя",
    deleteForAll: "Удалить у всех",
    messageDeleted: "Сообщение удалено",
    sendingProgress: "Отправка...",
    videoNote: "Видеозаметка...",
    voiceMessage: "Голосовое сообщение...",
    limitInfo: "До 250 MB",
    typeMessage: "Напишите сообщение...",
    chatUnavailable: "Чат недоступен",
    voiceMsgTooltip: "Голосовое сообщение",
    videoNoteTooltip: "Видеозаметка",
    imageLightboxTitle: "Просмотр",
    clearChatTitle: "Очистить чат",
    clearChatDesc: "Уверены, что хотите очистить историю?",
    onlyMe: "Только у меня",
    forEveryone: "У всех",
    photoAndVideo: "Фото и видео",
    document: "Документ",
    callUnavailable: "Звонок недоступен",
    audioCall: "Аудиозвонок",
    videoCall: "Видеозвонок",
    incomingCall: "Входящий вызов",
    calling: "Звоним...",
    talking: "Идет разговор",

    // Portfolio
    portfolioEmpty: "Портфолио пусто",
    addWorkBtn: "Добавить работу ({n}/{max})",
    newWorkTitle: "Новая работа",
    workTitlePlaceholder: "Название",
    workDescPlaceholder: "Описание",
    saveWorkBtn: "Сохранить",
    viewWorkTitle: "Просмотр",
    workAdded: "Работа добавлена",

    // Settings
    settingsTitle: "Настройки",
    themeTitle: "Тема оформления",
    themeDescription: "Выберите тему интерфейса",
    lightTheme: "Светлая",
    lightDescription: "Классическая светлая тема",
    darkTheme: "Тёмная",
    darkDescription: "Тёмная тема",
    systemTheme: "Системная",
    systemDescription: "Как в системе",
    notificationsTitle: "Уведомления",
    notificationsDescription: "Управление уведомлениями",
    pushNotifications: "Push-уведомления",
    emailNotifications: "Email-уведомления",
    privacyTitle: "Приватность",
    privacyDescription: "Конфиденциальность профиля",
    profileVisibility: "Видимость профиля",
    onlineStatusDescription: "Показывать статус онлайн",
    languageTitle: "Язык",
    languageDescription: "Выберите язык",
    accentColorTitle: "Цветовая палитра",
    accentColorDescription: "Основной цвет приложения",
    emerald: "Изумруд",
    ocean: "Океан",
    violet: "Фиолет",
    rose: "Роза",
    amber: "Янтарь",
    slate: "Сталь",
    saved: "Сохранено",
    settingSaved: "Обновлено",
    inviteFriends: "Пригласить друзей",
    shareLink: "Поделитесь ссылкой",
    linkCopied: "Скопировано!",
    joinSkillflow: "Присоединяйся к Skillflow!",
    share: "Поделиться",

    // Notifications
    justNow: "только что",
    minAgo: "{n} мин назад",
    hourAgo: "{n} ч назад",
    noNotifications: "Нет уведомлений",
    readAll: "Прочитать все",

    // About & How It Works
    aboutTitle: "О Skillflow",
    aboutIntro: "Skillflow — знание должно быть свободным.",
    mission: "Наша миссия",
    missionText: "Создать глобальное сообщество обмена навыками.",
    missionTextDetailed: "Мы создаём пространство, где люди свободно обмениваются знаниями без финансовых барьеров.",
    ourHistory: "Наша история",
    ourValues: "Наши ценности",
    contactUs: "Контакты",
    principlesTitle: "Наши принципы",
    openness: "Открытость",
    opennessDesc: "Знания доступны каждому.",
    communityAboutDesc: "Мы помогаем друг другу расти.",
    practicality: "Практичность",
    practicalityDesc: "Учёба через практику.",
    development: "Развитие",
    developmentDesc: "Делясь знаниями, растем сами.",
    simpleProcess: "Простой процесс",
    step1Title: "Создай профиль",
    step1Desc: "Добавь свои навыки.",
    step2Title: "Найди партнёра",
    step2Desc: "Найди общие интересы.",
    step3Title: "Договорись",
    step3Desc: "Свяжись в чате.",
    step4Title: "Учись",
    step4Desc: "Проведи сессию.",
    step5Title: "Отзыв",
    step5Desc: "Набирай репутацию.",
    whySkillExchange: "Почему обмен?",
    whySkillExchangeDesc: "Преимущества бартерного обучения.",
    step1Items: ["Регистрация", "Выбор навыков", "Уровень", "Фото"],
    step2Items: ["Поиск", "Совпадения", "Фильтры", "Уведомления"],
    step3Items: ["Чат", "Календарь", "Формат", "Материалы"],
    step4Items: ["Видео", "Таймер", "Запись", "Файлы"],
    step5Items: ["Оценка", "Отзыв", "Репутация", "Активность"],
    benefitsTitle: "Преимущества",
    benefitsList: ["Бесплатно", "Практика", "Нетворкинг", "Гибкость", "Опыт", "Фидбек"],

    // Categories
    categories: {
      programming: "Программирование",
      design: "Дизайн",
      music: "Музыка",
      languages: "Языки",
      fitness: "Фитнес",
      photography: "Фотография",
      marketing: "Маркетинг",
      business: "Бизнес",
      art: "Искусство",
      cooking: "Кулинария",
      sport: "Спорт",
      dancing: "Танцы",
      video: "Видеомонтаж",
      writing: "Письмо",
      psychology: "Психология",
      finance: "Финансы",
      education: "Наука",
      crafts: "Ремёсла",
      other: "Другое"
    },

    // Miscellaneous
    loading: "Загрузка…",
    commandMenu: "Меню команд",
    untilNextLevel: "{current}/{next} до «{level}»",
    rateExchange: "Оцените обмен",
    rateDesc: "Как прошло занятие с {name}?",
    rating1: "Ужасно",
    rating2: "Плохо",
    rating3: "Нормально",
    rating4: "Хорошо",
    rating5: "Отлично!",
    yourReview: "Ваш отзыв",
    reviewPlaceholder: "Ваш комментарий...",
    completeSession: "Завершить",
    chooseRatingError: "Выберите оценку",
  },
  en: {
    // Header & Nav
    skills: "Skills",
    howItWorks: "How it works",
    aboutUs: "About us",
    profile: "Profile",
    sessions: "Sessions",
    settings: "Settings",
    signIn: "Sign in",
    signUp: "Sign up",
    signOut: "Sign out",
    start: "Start",
    feed: "Feed",
    search: "Search",
    add: "Add",
    home: "Home",

    // Intro & Index
    marketOfTalents: "Exchange of talents",
    skillExchangeFree: "Free skill exchange",
    learnNewBySharing: "Learn something new by sharing",
    heroDescription: "Skillflow is a platform where people exchange knowledge directly.",
    createAccount: "Create account",
    howItWorksTitle: "How it works",
    howItWorksSubtitle: "Learn and share with others",
    findPartner: "Find partner",
    findPartnerDesc: "Smart algorithm finds mutual interests",
    exchangeSkills: "Exchange skills",
    exchangeSkillsDesc: "Teach and learn for free",
    reputationTitle: "Build reputation",
    reputationDesc: "Get reviews and status",
    safeTitle: "Safe",
    safeDesc: "Review system protects you",
    readyToStart: "Ready to start?",
    joinCommunity: "Join the community today",
    allRightsReserved: "All rights reserved.",

    // Auth
    welcomeBack: "Welcome back",
    enterDetailsSignIn: "Enter details to sign in",
    login: "Login",
    registration: "Registration",
    email: "Email",
    password: "Password",
    firstName: "First name",
    lastName: "Last name",
    noAccount: "No account?",
    haveAccount: "Have an account?",
    forgotPassword: "Forgot password?",
    processing: "Processing...",
    invalidEmail: "Invalid email",
    passwordMinLength: "Min 6 characters",
    passwordsDoNotMatch: "Passwords do not match",
    fillAllFields: "Fill all fields",
    chooseInterestError: "Select interest",
    maxSkillsError: "Maximum 5 skills",
    accountCreatedTitle: "Account created!",
    accountCreatedDesc: "Welcome to Skillflow!",
    invalidEmailPassword: "Invalid email or password",
    emailNotConfirmed: "Email not confirmed",
    welcomeBackTitle: "Welcome back!",
    welcomeBackDesc: "Login successful.",
    authRegError: "Reg error",
    authLoginError: "Login error",
    genericAuthError: "Error occurred",
    networkError: "Network error. Could not reach server. Please check your connection.",
    comingSoonTitle: "Soon",
    resetPasswordSoon: "Reset password coming soon",

    // Add Skill
    addNewSkill: "Add new skill",
    chooseWhatYouCanTeach: "What can you teach?",
    skillTitle: "Skill title",
    skillTitleLabel: "Skill title *",
    skillTitlePlaceholder: "e.g. React development",
    description: "Description",
    descriptionLabel: "Description *",
    descriptionPlaceholder: "Tell more about your experience...",
    category: "Category",
    categoryLabel: "Category *",
    selectCategory: "Select category",
    format: "Format",
    formatLabel: "Format *",
    selectFormat: "Select format",
    onlineFormat: "Online (Video)",
    offlineFormat: "Offline (Personal)",
    bothFormats: "Both",
    durationLabel: "Duration (min) *",
    skillLevel: "Your level",
    wantedSkills: "What in return?",
    wantedSkillsLabel: "Learn in return? *",
    wantedSkillsPlaceholder: "e.g. UI Design",
    addSkillBtn: "Add skill",
    skillAdded: "Skill added",
    skillAddedSuccess: "Skill added to feed",
    shareMastery: "Share mastery",
    shareMasteryDesc: "Describe your skill.",
    mainInfo: "Main info",
    detailsAndFormat: "Details",
    exchangeConditions: "Conditions",
    wishesAppearHere: "Wishes here...",
    wishesDesc: "List skills you want.",
    publishToFeed: "Publish",
    publishing: "Publishing...",
    skillAddedSuccessToast: "Added!",
    skillAddedSuccessDesc: "Skill is live",
    fillTitle: "Add title",
    fillDesc: "Add description",
    descTooLong: "Too long",
    maxWords: "Max {n} words",
    selectCategoryToast: "Select category",
    selectFormatToast: "Select format",
    setDuration: "15 - 180 min",
    setWanted: "Specify return",
    setWantedDesc: "Add at least one skill",
    wordsCount: "{n} / {max} words",
    shareSkillTitle: "Share skill",
    tellCommunity: "What are you master of?",
    whatCanYouDo: "What can you do?",
    detailedDescription: "Details",
    chooseSphere: "Choose sphere",
    whereLessons: "Where?",
    approxTime: "Session time (min)",
    examplesWanted: "e.g. English, Guitar...",
    publishSkillBtn: "Publish",
    refreshPage: "Refresh",
    skillsLoadError: "Error loading skills",
    skillAddError: "Could not add skill",
    skillDeleteError: "Could not delete skill",
    skillDeleteSuccess: "Skill deleted",
    selfExchangeError: "Cannot exchange with yourself",
    exchangeAlreadySent: "Request already sent",
    exchangeSendError: "Error sending request",
    exchangeRequestSent: "Exchange request sent",

    // Feed & Search
    communitySkills: "Community",
    findWhatToLearn: "What to learn?",
    searchPlaceholder: "Search...",
    noResults: "Nothing found",
    noSkillsFound: "No skills found matching your search.",
    tryChangeFilters: "Adjust filters",
    popularRequests: "Popular Requests",
    resetFilters: "Reset Filters",
    popularSkillList: {
      design: "Design",
      english: "English",
      guitar: "Guitar",
      photography: "Photography",
      marketing: "Marketing",
      yoga: "Yoga"
    },
    filters: "Filters",
    sortBy: "Sort",
    newest: "Newest",
    popular: "Popular",
    level: "Level",
    all: "All",
    allSkills: "All skills",

    // Profile & User Profile
    addInfoAboutYourself: "Add details in settings",
    rating: "rating",
    sessionsCount: "{n} sessions",
    skillsCount: "{n} skills",
    reputation: "reputation",
    mySkills: "My skills",
    portfolio: "Portfolio",
    city: "City",
    sessionHistory: "History",
    reviews: "Reviews",
    editProfile: "Edit profile",
    name: "First name",
    surname: "Last name",
    aboutMe: "About me",
    yourName: "Name",
    yourSurname: "Surname",
    tellAboutYourself: "About you...",
    save: "Save",
    saving: "Saving...",
    profileUpdated: "Updated",
    dataSaved: "Saved",
    error: "Error",
    couldNotSave: "Failed to save",
    noReviews: "No reviews",
    reviewsAppearAfterSessions: "Reviews after sessions",
    noSessions: "No sessions",
    noSkills: "No skills",
    noBio: "No info",
    back: "Back",
    message: "Message",
    delete: "Delete",
    sessionsAppearAfterExchange: "Sessions after exchange",
    sessionsCompleted: "completed",
    beginner: "Beginner",
    intermediate: "Intermediate",
    expert: "Expert",
    changeAvatar: "Change avatar",
    chooseAvatar: "Choose avatar",
    defaultAvatars: "Default",
    photoSetup: "Setup",
    dragToAlign: "Drag to align",
    chooseCustomPhoto: "Custom photo",
    fileLimitInfo: "{formats}, max {size}MB",
    orChooseCharacter: "Or character",
    cancel: "Cancel",
    done: "Done",
    inviteToExchange: "Exchange",
    online: "Online",
    offline: "Offline",
    telegram: "Telegram",
    location: "Location",
    avatar: "Avatar",
    anonymous: "Anonymous",
    someone: "Someone",
    user: "User",

    // Sessions & Exchange
    mySessions: "My sessions",
    manageYourSessions: "Manage sessions and reputation.",
    upcoming: "Upcoming",
    past: "Past",
    noUpcomingSessions: "No upcoming",
    findSkillsAndPlan: "Find skills and plan",
    findSkills: "Find skills",
    startSession: "Start",
    completed: "Completed",
    rate: "Rate",
    details: "Details",
    reviewSent: "Sent",
    min: "min",
    pending: "Pending",
    accepted: "Accepted",
    rejected: "Rejected",
    exchangeRequest: "Request",
    accept: "Accept",
    decline: "Decline",
    offerSent: "Sent",
    offerSentSuccess: "Request sent",
    incoming: "Incoming",
    outgoing: "Outgoing",
    active: "Active",
    archive: "Archive",
    noIncoming: "No incoming",
    noOutgoing: "No outgoing",
    noActive: "No active",
    noCompleted: "Empty",
    loginToSeeSessions: "Login to see",
    historyDescription: "History saved here.",
    acceptedExchangeDesc: "Open chat",
    completeExchange: "Complete",
    loadingRequests: "Loading...",
    partner: "Partner",
    from: "From",
    to: "To",
    requestAccepted: "Accepted!",
    requestRejected: "Rejected",
    requestAcceptedMsg: "{name} accepted.",
    requestRejectedMsg: "{name} rejected.",
    sessionCompletedToast: "Completed",
    thanksForReview: "Thanks!",
    viewDetails: "Details",
    exchangeRequestTitle: "New exchange request",
    exchangeRequestMsg: "{name} wants to exchange skills: {title}",
    exchangeRequestNotificationTitle: "Exchange request",
    exchangeRequestNotificationBody: "{name} offered an exchange for {title}",
    deleteSkillConfirm: "Delete?",
    deleteSkillDesc: "Deleted permanently.",
    preferredExchange: "Preferred",
    loginToMessage: "Login to message",
    loginToExchange: "Login to exchange",
    notificationSent: "Sent",
    write: "Write",
    offerExchange: "Exchange",
    minLabel: "min",

    // Chat & Calls
    emoji_smiles: "Smiles",
    emoji_gestures: "Gestures",
    emoji_hearts: "Hearts",
    emoji_fire: "Fire",
    emoji_food: "Food",
    emoji_nature: "Nature",
    imageProcessingError: "Image error",
    fileReadError: "Read error",
    chatLoadError: "Load error",
    cameraAccessError: "Camera error",
    micAccessError: "Mic error",
    loginToMessageChat: "Login to send",
    chatCleared: "Cleared",
    today: "Today",
    yesterday: "Yesterday",
    chatTitle: "Chat",
    isTyping: "typing...",
    demoChat: "Demo",
    onlineStatus: "Online",
    offlineStatus: "Offline",
    clearChatBtn: "Clear",
    clickToDownload: "Download",
    noRecipientPlaceholder: "Select user",
    startConversation: "Start chatting",
    deleteForMe: "For me",
    deleteForAll: "For all",
    messageDeleted: "Deleted",
    sendingProgress: "Sending...",
    videoNote: "Video note",
    voiceMessage: "Voice",
    limitInfo: "Max 250 MB",
    typeMessage: "Message...",
    chatUnavailable: "Unavailable",
    voiceMsgTooltip: "Voice",
    videoNoteTooltip: "Video",
    imageLightboxTitle: "View",
    clearChatTitle: "Clear",
    clearChatDesc: "Clear history?",
    onlyMe: "Only me",
    forEveryone: "Everyone",
    photoAndVideo: "Photo / Video",
    document: "Document",
    callUnavailable: "Unavailable",
    audioCall: "Audio",
    videoCall: "Video",
    incomingCall: "Incoming",
    calling: "Calling...",
    talking: "Talking",

    // Portfolio
    portfolioEmpty: "Empty",
    addWorkBtn: "Add ({n}/{max})",
    newWorkTitle: "New work",
    workTitlePlaceholder: "Title",
    workDescPlaceholder: "Desc",
    saveWorkBtn: "Save",
    viewWorkTitle: "View",
    workAdded: "Added",

    // Settings
    settingsTitle: "Settings",
    themeTitle: "Theme",
    themeDescription: "Choose theme",
    lightTheme: "Light",
    lightDescription: "Light theme",
    darkTheme: "Dark",
    darkDescription: "Dark theme",
    systemTheme: "System",
    systemDescription: "Follow system",
    notificationsTitle: "Notifications",
    notificationsDescription: "Manage",
    pushNotifications: "Push",
    emailNotifications: "Email",
    privacyTitle: "Privacy",
    privacyDescription: "Privacy",
    profileVisibility: "Visibility",
    onlineStatusDescription: "Online status",
    languageTitle: "Language",
    languageDescription: "Choose language",
    accentColorTitle: "Color",
    accentColorDescription: "Accent color",
    emerald: "Emerald",
    ocean: "Ocean",
    violet: "Violet",
    rose: "Rose",
    amber: "Amber",
    slate: "Slate",
    saved: "Saved",
    settingSaved: "Updated",
    inviteFriends: "Invite friends",
    shareLink: "Share link",
    linkCopied: "Copied!",
    joinSkillflow: "Join Skillflow!",
    share: "Share",

    // Notifications
    justNow: "now",
    minAgo: "{n}m ago",
    hourAgo: "{n}h ago",
    noNotifications: "None",
    readAll: "Read all",

    // About & How It Works
    aboutTitle: "About",
    aboutIntro: "Skillflow — knowledge exchange.",
    mission: "Mission",
    missionText: "Community of skills.",
    missionTextDetailed: "Free knowledge exchange.",
    ourHistory: "History",
    ourValues: "Values",
    contactUs: "Contacts",
    principlesTitle: "Principles",
    openness: "Openness",
    opennessDesc: "Accessible knowledge.",
    communityAboutDesc: "Mutual growth.",
    practicality: "Practice",
    practicalityDesc: "Learn by doing.",
    development: "Growth",
    developmentDesc: "Growth through sharing.",
    simpleProcess: "Process",
    step1Title: "Profile",
    step1Desc: "Add skills.",
    step2Title: "Partner",
    step2Desc: "Find peer.",
    step3Title: "Chat",
    step3Desc: "Arrange.",
    step4Title: "Learn",
    step4Desc: "Session.",
    step5Title: "Status",
    step5Desc: "Reputation.",
    whySkillExchange: "Why?",
    whySkillExchangeDesc: "Benefits.",
    step1Items: ["Reg", "Skills", "Level", "Photo"],
    step2Items: ["Search", "Matches", "Filters", "Notify"],
    step3Items: ["Chat", "Calendar", "Format", "Materials"],
    step4Items: ["Video", "Timer", "Record", "Files"],
    step5Items: ["Rating", "Review", "Reputation", "Activity"],
    benefitsTitle: "Benefits",
    benefitsList: ["Free", "Practice", "Network", "Flex", "Exp", "Feedback"],

    // Categories
    categories: {
      programming: "Programming",
      design: "Design",
      music: "Music",
      languages: "Languages",
      fitness: "Fitness",
      photography: "Photography",
      marketing: "Marketing",
      business: "Business",
      art: "Art",
      cooking: "Cooking",
      sport: "Sport",
      dancing: "Dancing",
      video: "Video",
      writing: "Writing",
      psychology: "Psychology",
      finance: "Finance",
      education: "Education",
      crafts: "Crafts",
      other: "Other"
    },

    // Miscellaneous
    loading: "Loading…",
    commandMenu: "Menu",
    untilNextLevel: "{current}/{next} until «{level}»",
    rateExchange: "Rate exchange",
    rateDesc: "Session with {name}?",
    rating1: "Terrible",
    rating2: "Bad",
    rating3: "Okay",
    rating4: "Good",
    rating5: "Great!",
    yourReview: "Review",
    reviewPlaceholder: "Comment...",
    completeSession: "Complete",
    chooseRatingError: "Rate please",
  }
};

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations.en | string) => any;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const { user } = useAuth();
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    if (saved === "ru" || saved === "en") return saved as Language;
    const browserLang = navigator.language.split("-")[0];
    return browserLang === "ru" ? "ru" : "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key: string) => {
    const keys = key.split(".");
    let current: any = translations[language];

    for (const k of keys) {
      if (current[k] === undefined) {
        // Fallback to en
        let fallback: any = translations.en;
        for (const fk of keys) {
          if (fallback[fk] === undefined) return key;
          fallback = fallback[fk];
        }
        return fallback;
      }
      current = current[k];
    }
    return current;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
