// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY || "";

// Guard against invalid URL to prevent crash
const isValidUrl = SUPABASE_URL && SUPABASE_URL.startsWith('http');

if (!isValidUrl || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn(
    "Supabase credentials are missing or invalid! " +
    "Check your environment variables for VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY."
  );
}

export const supabase = createClient<Database>(
  isValidUrl ? SUPABASE_URL : 'https://missing-url.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'missing-key',
  {
    auth: {
      storage: typeof window !== 'undefined' ? window.localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
